const data = [{
    'name': 'Peterson-Cordova',
    'amount': 220.45,
    'dueDate': '2022-07-18T07:34:53.742823',
    'frequency': 'monthly',
    'category': 'utilities',
    'paymentStatus': 'partial',
    'paymentMethod': 'cash',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'amount'
},
{
    'name': 'Weaver, Mathews and Hall',
    'amount': 292.51,
    'dueDate': '2023-11-03T07:34:53.764876',
    'frequency': 'quarterly',
    'category': 'rent',
    'paymentStatus': 'paid',
    'paymentMethod': 'cash',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': false,
    'alertsForPriceChanges': true,
    'customizableView': 'custom'
},
{
    'name': 'Riddle, Craig and Morales',
    'amount': 366.86,
    'dueDate': '2022-03-15T07:34:53.768686',
    'frequency': 'annually',
    'category': 'utilities',
    'paymentStatus': 'unpaid',
    'paymentMethod': 'other',
    'reminders': true,
    'notes': 'Tend name television he thousand drop.\nTogether order represent alone television manager rich. Actually sit onto.',
    'automaticBillDetection': true,
    'alertsForPriceChanges': true,
    'customizableView': 'custom'
},
{
    'name': 'Powell, Ramirez and Brooks',
    'amount': 926.26,
    'dueDate': '2022-03-02T07:34:53.776502',
    'frequency': 'annually',
    'category': 'utilities',
    'paymentStatus': 'paid',
    'paymentMethod': 'credit card',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': true,
    'customizableView': 'amount'
},
{
    'name': 'Rogers, Rodriguez and Johnson',
    'amount': 771.25,
    'dueDate': '2023-02-28T07:34:53.786043',
    'frequency': 'annually',
    'category': 'utilities',
    'paymentStatus': 'paid',
    'paymentMethod': 'cash',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'dueDate'
},
{
    'name': 'Bennett Group',
    'amount': 517.96,
    'dueDate': '2022-02-28T07:34:53.786325',
    'frequency': 'monthly',
    'category': 'other',
    'paymentStatus': 'partial',
    'paymentMethod': 'other',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': false,
    'alertsForPriceChanges': true,
    'customizableView': 'amount'
},
{
    'name': 'Lewis, Melendez and Mckenzie',
    'amount': 84.85,
    'dueDate': '2022-11-13T07:34:53.786917',
    'frequency': 'quarterly',
    'category': 'insurance',
    'paymentStatus': 'paid',
    'paymentMethod': 'other',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'custom'
},
{
    'name': 'Green, Schroeder and Sanchez',
    'amount': 814.85,
    'dueDate': '2023-12-04T07:34:53.787492',
    'frequency': 'monthly',
    'category': 'insurance',
    'paymentStatus': 'paid',
    'paymentMethod': 'cash',
    'reminders': false,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'amount'
},
{
    'name': 'Bailey Ltd',
    'amount': 708.99,
    'dueDate': '2023-11-01T07:34:53.787780',
    'frequency': 'quarterly',
    'category': 'rent',
    'paymentStatus': 'paid',
    'paymentMethod': 'cash',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': true,
    'customizableView': 'category'
},
{
    'name': 'Matthews Ltd',
    'amount': 327.96,
    'dueDate': '2022-06-23T07:34:53.788082',
    'frequency': 'annually',
    'category': 'utilities',
    'paymentStatus': 'paid',
    'paymentMethod': 'credit card',
    'reminders': false,
    'notes': 'Always military name including. Five kind relate. Play also recognize team open imagine behavior.',
    'automaticBillDetection': false,
    'alertsForPriceChanges': true,
    'customizableView': 'category'
},
{
    'name': 'Shah-Palmer',
    'amount': 78.47,
    'dueDate': '2022-07-19T07:34:53.788636',
    'frequency': 'monthly',
    'category': 'rent',
    'paymentStatus': 'unpaid',
    'paymentMethod': 'bank transfer',
    'reminders': false,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'dueDate'
},
{
    'name': 'Walker PLC',
    'amount': 706.9,
    'dueDate': '2023-02-14T07:34:53.788902',
    'frequency': 'quarterly',
    'category': 'utilities',
    'paymentStatus': 'unpaid',
    'paymentMethod': 'bank transfer',
    'reminders': false,
    'notes': 'Drug skill choice pick end. Attention floor life anyone fund choose. Money even bit thank. Often treat town everything fill bag.\nWhole win position. Left usually behavior reduce. Rock court none.',
    'automaticBillDetection': false,
    'alertsForPriceChanges': true,
    'customizableView': 'dueDate'
},
{
    'name': 'Owen, Hays and Hill',
    'amount': 599.54,
    'dueDate': '2023-02-02T07:34:53.825761',
    'frequency': 'quarterly',
    'category': 'rent',
    'paymentStatus': 'unpaid',
    'paymentMethod': 'credit card',
    'reminders': true,
    'notes': 'But live such generation not three campaign senior.\nInterest model remain join. Because I discover various.',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'custom'
},
{
    'name': 'Stephens Group',
    'amount': 597.37,
    'dueDate': '2022-11-30T07:34:53.826164',
    'frequency': 'annually',
    'category': 'rent',
    'paymentStatus': 'unpaid',
    'paymentMethod': 'bank transfer',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': false,
    'alertsForPriceChanges': true,
    'customizableView': 'amount'
},
{
    'name': 'Swanson Ltd',
    'amount': 786.16,
    'dueDate': '2022-01-11T07:34:53.826332',
    'frequency': 'annually',
    'category': 'other',
    'paymentStatus': 'partial',
    'paymentMethod': 'bank transfer',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': false,
    'alertsForPriceChanges': false,
    'customizableView': 'custom'
},
{
    'name': 'Cherry and Sons',
    'amount': 943.11,
    'dueDate': '2022-08-03T07:34:53.826623',
    'frequency': 'quarterly',
    'category': 'utilities',
    'paymentStatus': 'partial',
    'paymentMethod': 'cash',
    'reminders': false,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'amount'
},
{
    'name': 'Walker-Leon',
    'amount': 847.83,
    'dueDate': '2023-07-10T07:34:53.827080',
    'frequency': 'quarterly',
    'category': 'insurance',
    'paymentStatus': 'partial',
    'paymentMethod': 'bank transfer',
    'reminders': false,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': false,
    'customizableView': 'amount'
},
{
    'name': 'King LLC',
    'amount': 420.36,
    'dueDate': '2023-12-15T07:34:53.827363',
    'frequency': 'annually',
    'category': 'other',
    'paymentStatus': 'unpaid',
    'paymentMethod': 'bank transfer',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': true,
    'alertsForPriceChanges': true,
    'customizableView': 'custom'
},
{
    'name': 'Dougherty-Campbell',
    'amount': 682.84,
    'dueDate': '2022-05-24T07:34:53.827850',
    'frequency': 'monthly',
    'category': 'other',
    'paymentStatus': 'paid',
    'paymentMethod': 'cash',
    'reminders': false,
    'notes': 'Radio play sometimes cell around everyone rich million. Throw people city allow once teacher. Boy enter half carry.',
    'automaticBillDetection': true,
    'alertsForPriceChanges': true,
    'customizableView': 'dueDate'
},
{
    'name': 'Juarez, Austin and Yates',
    'amount': 946.72,
    'dueDate': '2022-08-28T07:34:53.828779',
    'frequency': 'monthly',
    'category': 'utilities',
    'paymentStatus': 'paid',
    'paymentMethod': 'credit card',
    'reminders': true,
    'notes': '',
    'automaticBillDetection': false,
    'alertsForPriceChanges': false,
    'customizableView': 'amount'
}]

export { data }